x-proxies: &proxies
  args:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - NO_PROXY=${NO_PROXY}
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
    - no_proxy=${no_proxy}

services:
  # Build services
  #
  debian:
    image: ${REGISTRY-ghcr.io/geti}/debian:${TAG-main}
    build:
      dockerfile_inline: |
        FROM debian AS debian
        LABEL release=1

        RUN apt update \
            && apt -y install \
                ca-certificates \
                curl=7.88.* \
                wget=1.21.* \
                netcat-traditional=1.10-* \
                gpg \
            && apt clean all \
            && rm -rf /var/cache/apt/*
      <<: *proxies
      additional_contexts:
        #- debian=docker-image://public.ecr.aws/debian/debian:12.8-slim
        - debian=docker-image://gcr.io/distroless/static-debian12:nonroot


  otx:
    image: ${REGISTRY-ghcr.io/geti}/otx2:${TAG-main}
    build:
      dockerfile_inline: |
        FROM debian AS otx

        ARG OTX_RELEASE_TAG

        WORKDIR /app

        RUN apt-get update && \
            apt-get install -y git \
            && apt clean all \
            && rm -rf /var/cache/apt/*

        RUN git clone --branch ${OTX_RELEASE_TAG} --single-branch https://github.com/open-edge-platform/training_extensions.git

        RUN cp -r /app/training_extensions/src/otx/tools/templates /model_templates
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - no_proxy=${no_proxy}
        - OTX_RELEASE_TAG=${OTX_RELEASE_TAG}
      additional_contexts:
        - debian=docker-image://public.ecr.aws/debian/debian:12.8-slim
        

  # Platform services
  # 
  platform_account:
    image: ${REGISTRY-ghcr.io/geti}/platform_account:${TAG-main}
    build:
      context: ./platform/services/account
      <<: *proxies
      additional_contexts:
        - credit_system=./libs/grpc_interfaces/src/grpc_interfaces/credit_system/go
        - account_service_grpc=./libs/grpc_interfaces/src/grpc_interfaces/account_service/go
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platform-account.rule=Host(`geti.localhost`) && (PathRegexp(`^/api/v[0-9]+/organizations(/.*)?$`) || PathRegexp(`^/api/v[0-9]+/logout/?$`) || PathRegexp(`^/api/v[0-9]+/profile/?$`) || PathRegexp(`^/api/v[0-9]+/personal_access_tokens(/.*)?$`))"
      - "traefik.http.routers.platform-account.priority=90"
      - "traefik.http.services.platform-account.loadbalancer.server.port=5002"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: ${DB_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      SPICEDB_ADDRESS: ${SPICEDB_ADDRESS}
      SPICEDB_TOKEN: ${SPICEDB_TOKEN}
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      GETI_NOTIFICATION_TOPIC: ${GETI_NOTIFICATION_TOPIC}
      LOGGING_CONFIG_DIR: /
      USERS_PER_ORG_LIMIT: 300
      FEATURE_FLAG_MANAGE_USERS_ROLES: "false"
      FEATURE_FLAG_MANAGE_USERS: "false"
      FEATURE_FLAG_REQ_ACCESS: "false"
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_started
      kafka:
        condition: service_healthy
      spicedb:
        condition: service_healthy

  platform_auth_proxy:
    image: ${REGISTRY-ghcr.io/geti}/platform_auth_proxy:${TAG-main}
    build:
      context: ./platform/services/auth_proxy
      <<: *proxies
      additional_contexts:
        - account_service_client=./libs/grpc_interfaces/src/grpc_interfaces/account_service/go
    environment:
      ACCOUNT_SERVICE_HOST: "platform_account"
      ACCOUNT_SERVICE_PORT: "5001"
      JWT_CERTIFICATE_PRIVATE_KEY_PATH: "/etc/geti-jwt-secret/tls.key"
      JWT_CERTIFICATE_PUBLIC_KEY_PATH: "/etc/geti-jwt-secret/tls.crt"
      HTTP_SERVER_PORT: "7002"
      UNAUTHORIZED_URLS: "/api/v1/profile,/api/v1/logout,/api/v1/onboarding/user,/api/v1/feature_flags"
      #JWKS_UPDATE_TIME: {{ .Values.certificate.jwksUpdateTime }} # 1s
      #JWKS_ENTRY_EXPIRATION: {{ .Values.certificate.jwksEntryExpiration }} # 15m
      #LOGGING_CONFIG_DIR: {{ .Values.global.logging_config_dir }}
      #ISS_INTERNAL: ...
      #AUD_INTERNAL: ...
      #ISS_EXTERNAL: ...
      #AUD_EXTERNAL: ...
      #REQUIRED_ROLES: ...
    volumes:
      - ./infrastructure/data/auth_proxy/certs:/etc/geti-jwt-secret:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platform-auth-proxy.rule=Host(`geti.localhost`) && PathRegexp(`^/api/v[0-9]+/set_cookie/?$`)"
      - "traefik.http.routers.platform-auth-proxy.priority=100"
      - "traefik.http.services.platform-auth-proxy.loadbalancer.server.port=7002"
    depends_on:
      platform_account:
        condition: service_started

  platform_credit:
    image: ${REGISTRY-ghcr.io/geti}/platform_credit:${TAG-main}
    build:
      context: ./platform/services/credit
      <<: *proxies
      additional_contexts:
        - libs=./libs 
    environment:
      POSTGRES_HOST: db
      POSTGRES_RO_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: creditsystem
      POSTGRES_SSLMODE: disable
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM: PLAIN
      ACCOUNT_SERVICE_HOST: platform_account
      ACCOUNT_SERVICE_PORT: 5001
      GRPC_SERVICE_PORT: 5556
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      platform_account:
        condition: service_started

  platform_notifier:
    image: ${REGISTRY-ghcr.io/geti}/platform_notifier:${TAG-main}
    build:
      context: ./platform/services/notifier
      <<: *proxies
      additional_contexts:
        - libs=./libs
    environment:
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      GETI_NOTIFICATION_TOPIC: ${GETI_NOTIFICATION_TOPIC}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      USE_START_TLS: "false"
    depends_on:
      kafka:
        condition: service_healthy
      mailhog:
        condition: service_started

  platform_observability:
    image: ${REGISTRY-ghcr.io/geti}/platform_observability:${TAG-main}
    build:
      context: ./platform/services/observability
      <<: *proxies
      additional_contexts:
        - libs=./libs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platform-observability.rule=Host(`geti.localhost`) && PathPrefix(`/api/v1/logs`)"
      - "traefik.http.routers.platform-observability.priority=55"
      - "traefik.http.services.platform-observability.loadbalancer.server.port=9000"

  platform_onboarding:
    image: ${REGISTRY-ghcr.io/geti}/platform_onboarding:${TAG-main}
    build:
      context: ./platform/services/onboarding
      <<: *proxies
      additional_contexts:
        - libs=./libs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platform-onboarding.rule=Host(`geti.localhost`) && (PathRegexp(`^/api/v[0-9]+/onboarding/user/?$`) || PathRegexp(`^/api/v[0-9]+/admin/onboarding/tokens/?$`))"
      - "traefik.http.routers.platform-onboarding.priority=88"
      - "traefik.http.services.platform-onboarding.loadbalancer.server.port=9000"
    environment:
      ACCOUNT_SERVICE_HOST: platform_account
      ACCOUNT_SERVICE_PORT: 5001
      CREDITS_SERVICE: platform_credit:5556
      FEATURE_FLAG_CREDIT_SYSTEM: "false"
      FEATURE_FLAG_FREE_TIER: "false"
      FEATURE_FLAG_SAAS_REQUIRE_INVITATION_LINK: "false"
      FEATURE_FLAG_REQ_ACCESS: "false"
      MARKETING_PLATFORM_URL: ""
      MARKETING_PLATFORM_FORM_NAME: ""
      MARKETING_PLATFORM_SITE_ID: ""
    depends_on:
      platform_account:
        condition: service_started
      platform_credit:
        condition: service_started

  platform_initial_user:
    image: ${REGISTRY-ghcr.io/geti}/platform_initial_user:${TAG-main}
    build:
      context: ./platform/services/initial_user
      <<: *proxies
      additional_contexts:
        - common_libs=./libs
        - platform_libs=./platform/libs
    command:
      - python
      - create_initial_user.py
    environment:
      INITIAL_USER_EMAIL: ${INITIAL_USER_EMAIL}
      INITIAL_USER_PASSWORD: ${INITIAL_USER_PASSWORD}
      LDAP_HOST: ${LDAP_HOST}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_ADMIN_USER: ${LDAP_ADMIN_USER}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      SPICEDB_ADDRESS: ${SPICEDB_ADDRESS}
      SPICEDB_TOKEN: ${SPICEDB_TOKEN}
      SPICEDB_CREDENTIALS: ${SPICEDB_CREDENTIALS}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DB_NAME}
      SPICEDB_POSTGRES_USER: ${DB_USER}
      SPICEDB_POSTGRES_PASSWORD: ${DB_PASSWORD}
      ACCOUNT_SERVICE_HOST: platform_account
      ACCOUNT_SERVICE_PORT: 5001
      FEATURE_FLAG_WORKSPACE_ACTIONS: "false"
      LOGGING_CONFIG_DIR: /
    depends_on:
      db:
        condition: service_healthy
      spicedb:
        condition: service_healthy
      platform_account:
        condition: service_started
      openldap:
        condition: service_started
    restart: "no"

  platform_user_directory:
    image: ${REGISTRY-ghcr.io/geti}/platform_user_directory:${TAG-main}
    build:
      context: ./platform/services/user_directory
      <<: *proxies
      additional_contexts:
        - libs=./libs
        - platform_libs=./platform/libs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platform-user-directory.rule=Host(`geti.localhost`) && (PathRegexp(`^/api/v[0-9]+/users/reset_password/?$`) || PathRegexp(`^/api/v[0-9]+/organizations/.*/users/create/?$`) || PathRegexp(`^/api/v[0-9]+/users/.*/update_password/?$`) || PathRegexp(`^/api/v[0-9]+/users/confirm_registration/?$`) || PathRegexp(`^/api/v[0-9]+/organizations/.*/users/invitations/?$`) || PathPrefix(`/confirm-action/registration/reset-password`))"
      - "traefik.http.routers.platform-user-directory.priority=85"
      - "traefik.http.services.platform-user-directory.loadbalancer.server.port=9000"
    environment:
      LDAP_HOST: ${LDAP_HOST}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_ADMIN_USER: ${LDAP_ADMIN_USER}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      SPICEDB_ADDRESS: ${SPICEDB_ADDRESS}
      SPICEDB_TOKEN: ${SPICEDB_TOKEN}
      SPICEDB_CREDENTIALS: ${SPICEDB_CREDENTIALS}
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      GETI_NOTIFICATION_TOPIC: ${GETI_NOTIFICATION_TOPIC}
      AUTH_MODE: ${AUTH_MODE}
      LOGS_DIR: /logs
      LOGGING_CONFIG_DIR: /
      USE_KUBECONFIG: "true"
    depends_on:
      openldap:
        condition: service_started
      kafka:
        condition: service_healthy
      spicedb:
        condition: service_healthy
    volumes:
      - user_directory_logs:/logs

  # IAI Services
  # 
  interactive_ai_auto_train:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/auto_train:${TAG-main}
    build:
      context: ./interactive_ai/services/auto_train
      <<: *proxies
      additional_contexts:
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/

  interactive_ai_dataset_import_export:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/dataset_import_export:${TAG-main}
    build:
      context: ./interactive_ai/services/dataset_ie
      <<: *proxies
      additional_contexts:
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive-ai-dataset-ie.rule=Host(`geti.localhost`) && (PathRegexp(`^/api/v[0-9]+/.*/datasets/uploads/resumable(/.*)?$`) || PathRegexp(`^/api/v[0-9]+/.*/(prepare-for-import|import-from-dataset|prepare-for-export)(/.*)?$`) || PathRegexp(`^/api/v[0-9]+/.*/datasets/.*/exports(/.*)?$`) || PathRegexp(`^/api/v[0-9]+/.*/datasets/.*:prepare-for-export.*$`))"
      - "traefik.http.routers.interactive-ai-dataset-ie.priority=75"
      - "traefik.http.services.interactive-ai-dataset-ie.loadbalancer.server.port=8000"
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_director:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/director:${TAG-main}
    build:
      context: ./interactive_ai/services/director
      <<: *proxies
      additional_contexts:
        - schemas=./interactive_ai/services/api
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
        - supported_models=./interactive_ai/supported_models/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive-ai-director.rule=Host(`geti.localhost`) && (PathRegexp(`^/api/v[0-9]+/.*/organizations/.*/status/?$`) || PathRegexp(`^/api/v[0-9]+/.*/projects/.*/status/?$`) || PathRegexp(`^/api/v[0-9]+/.*/workspaces/.*/(predictions|train|optimize|settings|datasets/active|configuration|tests)(/.*)?$`) || PathRegexp(`^/api/v[0-9]+/.*/projects/.*:train$`) || PathRegexp(`^/api/v[0-9]+/.*/models/.*:optimize$`) || PathRegexp(`^/api/v[0-9]+/.*/projects/.*/supported_algorithms/?$`) || PathRegexp(`^/api/v[0-9]+/.*/projects/.*/project_configuration/?$`) || PathRegexp(`^/api/v[0-9]+/.*/projects/.*/training_configuration/?$`))"
      - "traefik.http.routers.interactive-ai-director.priority=65"
      - "traefik.http.services.interactive-ai-director.loadbalancer.server.port=4999"
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_inference_gateway:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/inference_gateway:${TAG-main}
    build:
      context: ./interactive_ai/services/inference_gateway
      <<: *proxies
      additional_contexts:
        - iai_core=./interactive_ai/libs/iai_core_go/
        - modelmesh=./libs/grpc_interfaces/src/grpc_interfaces/model_mesh/go/pb
        - modelregistration=./libs/grpc_interfaces/src/grpc_interfaces/model_registration/go/pb
        - predict=./libs/grpc_interfaces/src/grpc_interfaces/predict/go/pb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive-ai-inference-gateway.rule=Host(`geti.localhost`) && (PathRegexp(`^/api/v[0-9]+/.*/pipelines/.*/status/?$`) || PathRegexp(`^/api/v[0-9]+/.*/pipelines/.*:(predict|explain|batch_predict|batch_explain|batch_predict_stream)$`) || PathRegexp(`^/api/v[0-9]+/.*/models/.*/status/?$`) || PathRegexp(`^/api/v[0-9]+/.*/models/.*:(predict|explain|batch_predict|batch_explain|batch_predict_stream)$`))"
      - "traefik.http.routers.interactive-ai-inference-gateway.priority=80"
      - "traefik.http.services.interactive-ai-inference-gateway.loadbalancer.server.port=7000"
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_jobs:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/jobs:${TAG-main}
    build:
      context: ./interactive_ai/services/jobs
      <<: *proxies
      additional_contexts:
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive-ai-jobs.rule=Host(`geti.localhost`) && PathRegexp(`^/api/v[0-9]+/.*/workspaces/.*/jobs(/.*)?$`)"
      - "traefik.http.routers.interactive-ai-jobs.priority=70"
      - "traefik.http.services.interactive-ai-jobs.loadbalancer.server.port=8000"
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_media:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/media:${TAG-main}
    build:
      context: ./interactive_ai/services/media
      <<: *proxies
      additional_contexts:
        - iai_core=./interactive_ai/libs/iai_core_go/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive-ai-media.rule=Host(`geti.localhost`) && PathRegexp(`^/api/v[0-9]+/.*/datasets/.*/media/images/.*/display/(full|thumb)$`)"
      - "traefik.http.routers.interactive-ai-media.priority=70"
      - "traefik.http.services.interactive-ai-media.loadbalancer.server.port=5002"
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_mlflow_geti_store:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/mlflow_geti_store:${TAG-main}
    build:
      <<: *proxies
      context: ./interactive_ai/services/mlflow_geti_store
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_model_registration:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/model_registration:${TAG-main}
    build:
      context: ./interactive_ai/services/model_registration
      <<: *proxies
      additional_contexts:
        - libs=./libs
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_project_import_export:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/project_import_export:${TAG-main}
    build:
      context: ./interactive_ai/services/project_ie
      <<: *proxies
      additional_contexts:
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive-ai-project-ie.rule=Host(`geti.localhost`) && (PathRegexp(`^/api/v[0-9]+/.*/projects/uploads/resumable(/.*)?$`) || PathRegexp(`^/api/v[0-9]+/.*/projects/.*:export$`) || PathRegexp(`^/api/v[0-9]+/.*/projects/.*/exports/.*/download/?$`) || PathRegexp(`^/api/v[0-9]+/.*/projects:import$`))"
      - "traefik.http.routers.interactive-ai-project-ie.priority=75"
      - "traefik.http.services.interactive-ai-project-ie.loadbalancer.server.port=8000"
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_resource:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/resource:${TAG-main}
    build:
      context: ./interactive_ai/services/resource
      <<: *proxies
      additional_contexts:
        - schemas=./interactive_ai/services/api
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
        - media_utils=./interactive_ai/libs/media_utils
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive-ai-resource.rule=Host(`geti.localhost`) && (PathRegexp(`^/api/v[0-9]+/healthz/?$`) || PathRegexp(`^/api/v[0-9]+/product_info/?$`) || PathPrefix(`/api/`))"
      - "traefik.http.routers.interactive-ai-resource.priority=50"
      - "traefik.http.services.interactive-ai-resource.loadbalancer.server.port=5000"
    depends_on:
      migration_job:
        condition: service_completed_successfully

  interactive_ai_visual_prompt:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/visual_prompt:${TAG-main}
    build:
      context: ./interactive_ai/services/visual_prompt
      <<: *proxies
      additional_contexts:
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
        - media_utils=./interactive_ai/libs/media_utils
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interactive-ai-visual-prompt.rule=Host(`geti.localhost`) && PathRegexp(`^/api/v[0-9]+/.*/pipelines/.*:prompt$`)"
      - "traefik.http.routers.interactive-ai-visual-prompt.priority=80"
      - "traefik.http.services.interactive-ai-visual-prompt.loadbalancer.server.port=8000"
    depends_on:
      migration_job:
        condition: service_completed_successfully

  migration_job:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/migration_job:${TAG-main}
    build:
      context: ./interactive_ai/migration_job
      <<: *proxies
      additional_contexts:
        - libs=./libs
        - data_migration=./interactive_ai/data_migration
    command:
      - /bin/sh
      - -c
      - >-
        mongodb_create_service_user &&
        run_migration &&
        create_s3_bucket
    environment:
      DATABASE_ADDRESS: ${DATABASE_ADDRESS}
      DATABASE_USERNAME: ${MONGODB_ROOT_USERNAME}
      DATABASE_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      DATABASE_USERNAME_SERVICE: ${DATABASE_USERNAME}
      DATABASE_PASSWORD_SERVICE: ${DATABASE_PASSWORD}
      SERVICE_USER_ALL_DB_ROLES: ${SERVICE_USER_ALL_DB_ROLES}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      MONGODB_CREDENTIALS_PROVIDER: local
      S3_ADDRESS: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
      s3:
        condition: service_started
    restart: "no"

  # IAI Workflows
  # 
  interactive_ai_workflows_dataset_import_export:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/workflows_dataset_import_export:${TAG-main}
    build:
      context: ./interactive_ai/workflows/geti_domain/dataset_ie
      <<: *proxies
      additional_contexts:
        - common=./interactive_ai/workflows/geti_domain/common
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
        - media_utils=./interactive_ai/libs/media_utils

  interactive_ai_workflows_model_test:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/workflows_model_test:${TAG-main}
    build:
      context: ./interactive_ai/workflows/geti_domain/model_test
      <<: *proxies
      additional_contexts:
        - common=./interactive_ai/workflows/geti_domain/common
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
        - media_utils=./interactive_ai/libs/media_utils

  interactive_ai_workflows_project_import_export:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/workflows_project_import_export:${TAG-main}
    build:
      context: ./interactive_ai/workflows/geti_domain/project_ie
      <<: *proxies
      additional_contexts:
        - common=./interactive_ai/workflows/geti_domain/common
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
        - media_utils=./interactive_ai/libs/media_utils
        - data_migration=./interactive_ai/data_migration

  interactive_ai_workflows_optimize:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/workflows_optimize:${TAG-main}
    build:
      context: ./interactive_ai/workflows/geti_domain/optimize
      <<: *proxies
      additional_contexts:
        - common=./interactive_ai/workflows/geti_domain/common
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
        - media_utils=./interactive_ai/libs/media_utils

  interactive_ai_workflows_train:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/workflows_train:${TAG-main}
    build:
      context: ./interactive_ai/workflows/geti_domain/train
      <<: *proxies
      additional_contexts:
        - common=./interactive_ai/workflows/geti_domain/common
        - libs=./libs
        - iai_core=./interactive_ai/libs/iai_core_py/
        - media_utils=./interactive_ai/libs/media_utils

  interactive_ai_workflows_otx_v2_gpu:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/otx_v2_gpu:${TAG-main}
    build:
      context: ./interactive_ai/workflows/otx_domain/trainer/otx_v2
      dockerfile: ./gpu/Dockerfile
      <<: *proxies
      additional_contexts:
        - libs=./libs

  interactive_ai_workflows_otx_v2_xpu:
    image: ${REGISTRY-ghcr.io/geti}/interactive_ai/otx_v2_xpu:${TAG-main}
    build:
      context: ./interactive_ai/workflows/otx_domain/trainer/otx_v2
      dockerfile: ./xpu/Dockerfile
      <<: *proxies
      additional_contexts:
        - libs=./libs

  # Web UI
  # 
  web:
    image: ${REGISTRY-ghcr.io/geti}/web_ui:${TAG-main}
    build:
      context: ./web_ui
      <<: *proxies
      additional_contexts:
        - nginx_image=docker-image://${NGINX_IMAGE}
        - node_image=docker-image://${NODE_IMAGE}
        - docs_context=./docs 
        - api_context=./interactive_ai/services/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geti-web.rule=(Host(`geti.localhost`) && !(PathPrefix(`/dex`))) || Host(`web.geti.localhost`)"
      - "traefik.http.routers.geti-web.priority=1"
      - "traefik.http.services.geti-web.loadbalancer.server.port=3000"


  # Infrastructure
  #
  # traefik
  reverse-proxy:
    image: traefik:v3.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"
    restart: unless-stopped

  # https://geek-cookbook.funkypenguin.co.nz/docker-swarm/authelia/
  # https://www.authelia.com/integration/proxies/traefik/
  authelia:
    image: 'authelia/authelia'
    restart: 'unless-stopped'
    volumes:
      - '${PWD}/infrastructure/data/authelia/config:/config'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`auth.geti.localhost`)"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"



      # "traefik.enable": 'true'
      # "traefik.http.routers.authelia.rule": 'Host(`auth.geti.localhost`)'
      # "traefik.http.routers.authelia.entryPoints": 'https'
      # "traefik.http.routers.authelia.tls": 'true'
      # "traefik.http.middlewares.authelia.forwardAuth.address": 'http://authelia:9091/api/authz/forward-auth'
      ## The following commented line is for configuring the Authelia URL in the proxy. We strongly suggest this is
      ## configured in the Session Cookies section of the Authelia configuration.
      # traefik.http.middlewares.authelia.forwardAuth.address: 'http://authelia:9091/api/authz/forward-auth?authelia_url=https%3A%2F%2Fauth.example.com%2F'
      # traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      # traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Remote-User,Remote-Groups,Remote-Email,Remote-Name'

    # dex:
    # https://geek-cookbook.funkypenguin.co.nz/docker-swarm/traefik-forward-auth/dex-static/
  dex:
    image: dexidp/dex
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '${PWD}/infrastructure/data/dex/config.yml:/config.yml:ro'
      - '${PWD}/infrastructure/data/dex/dex.db:/var/dex/dex.db'
      - '${PWD}/web_ui/dex_templates:/web'
    command: ['dex', 'serve','/config.yml']
    #command: ['/bin/sh']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dex.rule=(Host(`geti.localhost`) && PathPrefix(`/dex`))"
      - "traefik.http.services.dex.loadbalancer.server.port=5556"
    environment:
      DEX_DOMAIN: "dex.geti.localhost"
    restart: unless-stopped


  kafka:
    image: bitnami/kafka:3.7.1-debian-12-r7
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9094,PLAINTEXT_HOST://:9095
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9095
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      BITNAMI_DEBUG: yes
    ports:
      - 9095:9095
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--version"]
      start_period: 15s
      interval: 10s
      retries: 5
      timeout: 10s
    restart: always

  s3:
    image: chrislusf/seaweedfs:3.69
    restart: always
    command: server -s3 -dir=/data
    ports:
      - "8333:8333"
    volumes:
      - s3_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fileservice.rule=Host(`geti.localhost`) && PathPrefix(`/api/v1/fileservice/`)"
      - "traefik.http.routers.fileservice.priority=60"
      - "traefik.http.routers.fileservice.middlewares=fileservice-strip@docker"
      - "traefik.http.middlewares.fileservice-strip.stripprefix.prefixes=/api/v1/fileservice"
      - "traefik.http.services.fileservice.loadbalancer.server.port=8333"

  openldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "Geti Local"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
    ports:
      - "389:389"
    restart: always

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
    restart: always

  spicedb:
    image: authzed/spicedb:v1.34.0
    command: serve --grpc-preshared-key "${SPICEDB_TOKEN}"
    restart: always
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-v", "-addr=localhost:50051"]
      start_period: 15s
      interval: 10s
      retries: 5
      timeout: 10s

  db:
    image: postgres:14.13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=${DB_NAME} --username=${DB_USER}"]
      start_period: 20s
      interval: 10s
      retries: 5
      timeout: 10s
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--username", "${MONGODB_ROOT_USERNAME}", "--password", "${MONGODB_ROOT_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping').ok"]
      start_period: 20s
      interval: 10s
      retries: 5
      timeout: 10s
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  s3_data:
  postgres_data:
  mongodb_data:
  user_directory_logs:

networks:
  default:
    name: geti
